// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gunaiiqtvzurqppunitk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bmFpaXF0dnp1cnFwcHVuaXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjczNzcsImV4cCI6MjA2NDUwMzM3N30.t2HFF_Zp3OhF6snDeABn7Urn4v-sfUY2sDvv51_dH4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);